export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_LIST_FAIL = 'ALBUM_LIST_FAIL';

export const ALBUM_DETAILS_REQUEST = 'ALBUM_DETAILS_REQUEST';
export const ALBUM_DETAILS_SUCCESS = 'ALBUM_DETAILS_SUCCESS';
export const ALBUM_DETAILS_FAIL = 'ALBUM_DETAILS_FAIL';
